# Generated by Django 6.0.6 on 2026-06-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Identifiant CVE')),
                ('score_cvss', models.FloatField(blank=True, null=True, verbose_name='Score CVSS')),
                ('base_severity', models.CharField(db_index=True, max_length=20, verbose_name='Gravité')),
                ('type_cwe', models.CharField(max_length=32, verbose_name='Type CWE')),
                ('score_epss', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Score EPSS')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('editeur', models.CharField(db_index=True, max_length=255, verbose_name='Éditeur')),
                ('produit', models.TextField(blank=True, verbose_name='Produit(s)')),
                ('versions_affectees', models.TextField(blank=True, verbose_name='Versions affectées')),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVE',
                'ordering': ['cve_id'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_anssi', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Identifiant ANSSI')),
                ('titre_anssi', models.CharField(max_length=255, verbose_name='Titre')),
                ('type_bulletin', models.CharField(db_index=True, max_length=16, verbose_name='Type')),
                ('date_publication', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date de publication')),
                ('lien_bulletin', models.URLField(blank=True, max_length=255, verbose_name='Lien')),
                ('cves', models.ManyToManyField(related_name='bulletins', to='vulnerabilities.cve', verbose_name='CVE citées')),
            ],
            options={
                'verbose_name': 'bulletin',
                'verbose_name_plural': 'bulletins',
                'ordering': ['-date_publication', 'id_anssi'],
            },
        ),
    ]
